### ISSUE TITLE
annulation en secouant

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#10]
affiche un message d'alerte "undo"
a desactiver

**Comment by vmoore-paris** [comment]
Reproduit sur l'ipad
Affiche "undo typing"

**Comment by vmoore-paris** [comment]
Comportment par défaut d'iOS (sauf si désactivation dans paramètres depuis iOS9)
Il reste en focus sur le dernier champ texte rempli et semble garder l'historique quels que soient les scripts pour désactiver le focus et vider le champ...
Seule solution, forcer la désactivation du geste shake pour l'application via plugin.
(donc pas de possibilité de vider un formulaire en un "shake" du coup)

**Comment by pmlaroche-agoralogie** [comment]
testé ios 9.1 ok
