### ISSUE TITLE
navigation par le menu principal non stable

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#17]
Karim :  (iPhone 5s, iOS 8.4.1, smarttoc version 0.7.0, installé aujourd'hui à 17:00) la navigation par le menu principal ne fonctionne pas : les entrées "Mes résultast", "Mon journal de bord", etc. me renvoient sur la page d'accueil.
Philippe : le navigation me renvoie "parfois" sur la page d'accueil, sinon fonctionne bien

**Comment by vmoore-paris** [comment]
Non reproduit en émulation sur iPhone5s / iOs 8.4...
Est-ce que les précédentes étapes se sont bien affichées? 
(c'est à dire le consentement et le questionnaire démographique)

**Comment by pmlaroche-agoralogie** [comment]
> j'accède aux menus mais c'est très laborieux, si je fais un simple clic  ça me ramène à la homepage de l'app, si je fais un clic long puis dans le sous-menu "open" ça ouvre bien les pages correspondantes
