### ISSUE TITLE
bouton pour fermer l'affichage des restitutions non visible 

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#18]
et barre android difficile à faire apparaître : utilisateur "coincé"
sur android sur un affichage 360*640

**Comment by vmoore-paris** [comment]
Possibilité d'avoir une capture d'écran? photo? (pour me rendre compte)
La version android aussi peut-être.

**Comment by pmlaroche-agoralogie** [comment]
non repetable
