### ISSUE TITLE
mode non connecté : menu n'apparait pas sur page d'accueil

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#22]
taille d'affichage reste sur 0x0 ?

**Comment by pmlaroche-agoralogie** [comment]
juliette le 9/12 : J'ai téléchargé la dernière version en date et il ne m'est pas possible d'accéder au menu si je ne suis pas connectée à internet.

**Comment by vmoore-paris** [comment]
Je viens de tester à nouveau en local certificat ko pour iOs pour l'instant)
et je ne reproduis pas.
Besoin de plus d'informations
(scénarios, capture d'écrans)

**Comment by pmlaroche-agoralogie** [comment]
lancement sur android GT-I9100 android 4.1.2
Kernel 3.0.31
au lancement,le programme  reste à la page initialisation, et n'arrive jamais plus loin.

**Comment by pmlaroche-agoralogie** [comment]
cas tres difficile à reproduire, donc rare : on attends une seconde remarque pour evaluer si on doit agir plus
