### ISSUE TITLE
données du questionnaire hebdo non remonté en base

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#23]
après échange avec Juliette, qui a eu une alerte ce dimanche 29, et a rempli son questionnaire hebdomadaire, il n'y a pas de traca dans le slogs : je pense que les données du questionnaire hebdo ne sont pas renvoyées.
il n'y a de sa part que :
 [29/Nov/2015:13:11:51 +0100] "GET /horaires_smarttocv1.php?uid=5777fccc321703e45ab53c42a7e17ab3 HTTP/1.1" 200 2879 "-" "Mozilla/5.0 (Linux; Android 4.4.4; SM-G360F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36"
 [29/Nov/2015:13:18:37 +0100] "-" 408 0 "-" "-"
donc il manque les appels de type 
37.162.153.125 - - [28/Nov/2015:10:18:47 +0100] "GET /mobile/mobilerpc.php?answer={%22sid%22:%22916553%22,%22timestamp%22:1448702306,%22916553X495X1388%22:%22OU1%22,%22916553X497X1390%22:%2226%22,%22916553X502X1395%22:%22A1%22,%22916553X498X1391%22:%2229%22,%22916553X499X1392%22:%226%22,%22916553X500X1393%22:%220%22,%22916553X501X1394%22:%220%22,%22916553X504X1396%22:%2218%22,%22916553X503X1397%22:%2260%22,%22916553X505X1398%22:%225777fccc321703e45ab53c42a7e17ab3%22} HTTP/1.1" 200 747 "-" "Mozilla/5.0 (Linux; Android 4.4.4; SM-G360F Build/KTU84P) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/33.0.0.0 Mobile Safari/537.36"

**Comment by vmoore-paris** [comment]
En attente de la prochaine connexion/questionnaire pour définitivement statuer sur l'issue.

**Comment by pmlaroche-agoralogie** [comment]
j'ai bricolé les alertes pour me programmer un questionnaire hebdo, tout a marcher de manière normale ; sauf contre-ordre, je mise sur un deconnexion de juliette.
