### ISSUE TITLE
icones mises en place dans le dossier html/res non utilisées

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#25]
sous ios, les icones restent celles de phonegap, alors que les fichiers icones ont été mises à jour avec des versions dans la charte

**Comment by vmoore-paris** [comment]
Je n'ai pas le souci sur l'iPad (iOS 8.1)
Je vois l'ancienne icône sur l'émulateur... 
mais c'est peut-être la méthode de compilation en local qui ne les prends pas en compte 
Ou du cache dans tous les cas?
Je laisse de côté pour l'instant.

**Comment by vmoore-paris** [comment]
D'après ce que je vois sur le net, il est possible qu'il y ait aussi un souci avec la taille des icones/splashcreen
http://stage.docs.phonegap.com/configure/icons/
http://stage.docs.phonegap.com/configure/splash-screens/
(mais du coup je ne comprends pas pourquoi l'iPad les trouvent car le splashscreen n'est pas à la bonne taille pour lui non plus...)
