### ISSUE TITLE
sur la page "âge" écrit en anglais "done"

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#29]
est ce parce que l'application declare etre de preference en anglais, ou manque de traduction dans le framework ?

**Comment by vmoore-paris** [comment]
https://github.com/don/KeyboardToolbarRemover/blob/6685b402469a06911fed93ed8d4e3796f8904075/README.md

**Comment by vmoore-paris** [comment]
https://github.com/cjpearson/cordova-plugin-keyboard
