### ISSUE TITLE
QCM malpratique

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#30]
il est un peu difficile de cocher pour choisir par exemple "ou etes vous" : il faut appuyer sur le texte, les gens appuient sur le bouton radio (qui est inactif)
si l'apparence pouvait être légérement amélioré, ça serait mieux

**Comment by kndiaye** [comment]
il faudrait agrandir la taille de la font et donc les bouton radios et les espacer
