### ISSUE TITLE
envoi pdf : choix des questions malpratiques

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#36]
le fonctionnement du choix des questions est difficile à comprendre : parfois en cliquant, glissant tapotant on arrive à en rendre un rouge, mais c'est difficile à repeter.
un texte serait le bienvenu, peut etre en haut de page, je propose en premier jet : 
Double-cliquer une question pour la rendre rouge, elle sera ainsi exclue de la restitution

**Comment by vmoore-paris** [comment]
A tester sur device
Si ok, faire texte explicatif

**Comment by vmoore-paris** [comment]
Selection ok sur device (simple click)
En attente de retour texte explicatif si besoin
