### ISSUE TITLE
clavier recouvre case saisie journal

### ISSUE THREAD

**Issue by pmlaroche-agoralogie** [pmlaroche-agoralogie/smarttoc#38]
quand on tape le texte dans le journal de bord, le clavier recouvre totalement la case
![screenshot_2015-12-15-13-20-04](https://cloud.githubusercontent.com/assets/547222/11814876/666a89b8-a349-11e5-801b-fa9d659d5124.png)

**Comment by vmoore-paris** [comment]
Non reproduit sur iOs emulateur (et il me semble qu'il n'y avait pas de problème sur device iOs non plus)
A priori propre à Android.

**Comment by pmlaroche-agoralogie** [comment]
je viens de faire un test avec notre tablette nexus, je confirme : quand on clique sur un champs de saisie, le clavier surgit du bas, et ne peux pas etre deplacé.

**Comment by vmoore-paris** [comment]
Notes:
http://stackoverflow.com/questions/20223617/phonegap-keyboardshrinksview-and-position-fixed-on-ios-not-applying-correctly
http://stackoverflow.com/questions/10076148/phonegap-is-there-a-way-to-stop-the-keyboard-from-resizing-the-view
http://stackoverflow.com/questions/22715485/soft-keyboard-makes-the-cordova-view-shrink

**Comment by vmoore-paris** [comment]
A priori ok avec fullscreen false
