### ISSUE TITLE
modalités réponses : question hebdo "avez-vous pris du plaisir dans vos activités cette semaine"

### ISSUE THREAD

**Issue by kndiaye** [pmlaroche-agoralogie/smarttoc#50]
Remplacer les étiquettes des bulles par : "pas du tout"  et  "beaucoup"

(code question : "plaisir", page08;  #tpl:sl13#frq:x# )

**Comment by kndiaye** [comment]
Il faudrait lui assigner le template #5 : tpl_sl5.tpl.html
("Pas du tout" à "Enormément")

**Comment by pmlaroche-agoralogie** [comment]
fait
